# Generated by Django 6.0.3 on 2026-04-03 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BREAKFAST', 'Завтраки'), ('FIRST', 'Первые блюда'), ('SECOND', 'Вторые блюда'), ('SALAD', 'Салаты'), ('SNACK', 'Закуски'), ('DESSERT', 'Десерты и выпечка'), ('DRINK', 'Напитки'), ('SAUCE', 'Соусы и заправки'), ('PRESERVES', 'Заготовки')], default='SECOND', max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RUS', 'Русская'), ('ITA', 'Итальянская'), ('GEO', 'Грузинская'), ('CHI', 'Китайская'), ('JAP', 'Японская'), ('FRE', 'Французская'), ('UZB', 'Узбекская'), ('EUR', 'Европейская'), ('PAN', 'Пан-азиатская'), ('OTH', 'Другая')], default='OTH', max_length=3, verbose_name='Кухня мира')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Кухня',
                'verbose_name_plural': 'Кухни',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('QUICK', 'Быстро'), ('EASY', 'Просто'), ('GOURMET', 'Празднично'), ('VEGAN', 'Веганское'), ('VEGETARIAN', 'Вегетарианское'), ('LENTEN', 'Постное'), ('GF', 'Без глютена'), ('PP', 'Правильное питание'), ('KIDS', 'Для детей'), ('OVEN', 'В духовке'), ('MULTI', 'В мультиварке'), ('NOBAKE', 'Без выпечки'), ('GRILL', 'На гриле'), ('SPICY', 'Острое'), ('LOWCAL', 'Низкокалорийное')], max_length=50, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название рецепта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('instructions', models.TextField(verbose_name='Шаги приготовления')),
                ('cooking_time', models.PositiveIntegerField(help_text='в минутах', verbose_name='Время приготовления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='cooking.profile', verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='cooking.category', verbose_name='Категория')),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='cooking.cuisine', verbose_name='Кухня')),
                ('tags', models.ManyToManyField(related_name='recipes', to='cooking.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ингредиента')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Например: 1.5 или 500', max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(choices=[('G', 'г'), ('KG', 'кг'), ('ML', 'мл'), ('L', 'л'), ('PC', 'шт'), ('TBSP', 'ст. л.'), ('TSP', 'ч. л.'), ('CUP', 'стакан'), ('PINCH', 'щепотка')], default='G', max_length=10, verbose_name='Единица измерения')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cooking.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
    ]
