# Generated by Django 6.0.3 on 2026-03-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('first_courses', 'Первые блюда'), ('second_courses', 'Вторые блюда'), ('salads', 'Салаты'), ('desserts', 'Десерты')], default='first_courses', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cuisine', models.CharField(max_length=100)),
                ('ingredients', models.JSONField()),
                ('instructions', models.TextField()),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cooking.mealtype')),
            ],
        ),
    ]
