# Generated by Django 6.0.3 on 2026-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(choices=[('Russian', 'Русская'), ('Italian', 'Итальянская'), ('Georgian', 'Грузинская'), ('Chinese', 'Китайская'), ('Japanese', 'Японская'), ('French', 'Французская'), ('Uzbek', 'Узбекская'), ('European', 'Европейская'), ('Pan_Asian', 'Пан-азиатская'), ('Other', 'Другая')], default='Other', max_length=10, verbose_name='Кухня мира'),
        ),
    ]
