# Generated by Django 6.0.3 on 2026-04-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('G', 'г.'), ('KG', 'кг.'), ('ML', 'мл.'), ('L', 'л.'), ('PC', 'шт.'), ('TBSP', 'ст. л.'), ('TSP', 'ч. л.'), ('CUP', 'стакан'), ('PINCH', 'щепотка')], default='G', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(verbose_name='Время приготовления'),
        ),
    ]
