# Generated by Django 6.0.3 on 2026-03-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
