# Generated by Django 6.0.3 on 2026-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_alter_mealtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='slug',
            field=models.SlugField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
