# Generated by Django 6.0.3 on 2026-04-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_alter_ingredient_amount_alter_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('G', 'г.'), ('KG', 'кг.'), ('ML', 'мл.'), ('L', 'л.'), ('PC', 'шт.'), ('TBSP', 'ст. л.'), ('TSP', 'ч. л.'), ('CUP', 'стакан'), ('PINCH', 'щепотка')], default='G', max_length=10, verbose_name='Единица измерения'),
        ),
    ]
