# Generated by Django 6.0.3 on 2026-04-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_alter_cuisine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('BREAKFAST', 'Завтраки'), ('FIRST_COURSE', 'Первые блюда'), ('SECOND_COURSE', 'Вторые блюда'), ('SALAD', 'Салаты'), ('SNACK', 'Закуски'), ('DESSERT', 'Десерты и выпечка'), ('DRINK', 'Напитки'), ('SAUCE', 'Соусы и заправки'), ('PRESERVES', 'Заготовки')], default='SECOND_COURSE', max_length=50, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(choices=[('RUSSIAN', 'Русская'), ('ITALIAN', 'Итальянская'), ('GEORGIAN', 'Грузинская'), ('CHINESE', 'Китайская'), ('JAPANESE', 'Японская'), ('FRENCH', 'Французская'), ('UZBEK', 'Узбекская'), ('EUROPEAN', 'Европейская'), ('PAN_ASIAN', 'Пан-азиатская'), ('OTHER', 'Другая')], default='OTHER', max_length=10, verbose_name='Кухня мира'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[('QUICK', 'Быстро'), ('EASY', 'Просто'), ('GOURMET', 'Празднично'), ('VEGAN', 'Веганское'), ('VEGETARIAN', 'Вегетарианское'), ('LENTEN', 'Постное'), ('GLUTEN_FREE', 'Без глютена'), ('PP', 'Правильное питание'), ('KIDS', 'Для детей'), ('OVEN', 'В духовке'), ('MULTICOOKER', 'В мультиварке'), ('NO_BAKE', 'Без выпечки'), ('GRILL', 'На гриле'), ('SPICY', 'Острое'), ('LOW_CAL', 'Низкокалорийное'), ('PARTY', 'Вечеринка'), ('SOUP', 'Суп'), ('FAMILY', 'Семейное'), ('BREAKFAST', 'Завтрак'), ('HEARTY', 'Сытное')], default='EASY', max_length=50, unique=True, verbose_name='Тег'),
        ),
    ]
