# Generated by Django 6.0.3 on 2026-03-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_mealtype_slug_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
