# Generated by Django 6.0.3 on 2026-04-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
