# Generated by Django 6.0.3 on 2026-04-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_alter_category_category_alter_cuisine_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
