# Generated by Django 6.0.3 on 2026-03-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_alter_mealtype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtype',
            name='slug',
        ),
    ]
